--
-- PostgreSQL database dump
--

\restrict NPAf9eP8ULVtHMkjEz7n1PtB7fB40sJyz27aD76mnHoFaKDzJbTzcSmoKaFpLFg

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-02-11 23:08:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 16648)
-- Name: attendance; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    date date,
    name character varying(255),
    roll_no character varying(255),
    status character varying(255),
    subject character varying(255)
);


ALTER TABLE public.attendance OWNER TO admin;

--
-- TOC entry 225 (class 1259 OID 16647)
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.attendance_id_seq OWNER TO admin;

--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 225
-- Name: attendance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.attendance_id_seq OWNED BY public.attendance.id;


--
-- TOC entry 224 (class 1259 OID 16637)
-- Name: complaints; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.complaints (
    id bigint NOT NULL,
    anonymous boolean NOT NULL,
    category character varying(255),
    department character varying(255),
    description character varying(1000),
    roll_no character varying(255),
    status character varying(255),
    student_name character varying(255),
    sub_category character varying(255)
);


ALTER TABLE public.complaints OWNER TO admin;

--
-- TOC entry 223 (class 1259 OID 16636)
-- Name: complaints_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.complaints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.complaints_id_seq OWNER TO admin;

--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 223
-- Name: complaints_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.complaints_id_seq OWNED BY public.complaints.id;


--
-- TOC entry 220 (class 1259 OID 16619)
-- Name: feedback; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.feedback (
    id bigint NOT NULL,
    name character varying(255),
    rating character varying(255),
    suggestion character varying(255)
);


ALTER TABLE public.feedback OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 16618)
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16628)
-- Name: leave_application; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.leave_application (
    id bigint NOT NULL,
    branch character varying(255),
    name character varying(255),
    reason character varying(255),
    roll_no character varying(255),
    status character varying(255),
    year character varying(255),
    from_date date,
    leave_type character varying(255),
    to_date date
);


ALTER TABLE public.leave_application OWNER TO admin;

--
-- TOC entry 221 (class 1259 OID 16627)
-- Name: leave_application_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.leave_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4869 (class 2604 OID 16651)
-- Name: attendance id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attendance ALTER COLUMN id SET DEFAULT nextval('public.attendance_id_seq'::regclass);


--
-- TOC entry 4868 (class 2604 OID 16640)
-- Name: complaints id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.complaints ALTER COLUMN id SET DEFAULT nextval('public.complaints_id_seq'::regclass);


--
-- TOC entry 4877 (class 2606 OID 16656)
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- TOC entry 4875 (class 2606 OID 16646)
-- Name: complaints complaints_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.complaints
    ADD CONSTRAINT complaints_pkey PRIMARY KEY (id);


--
-- TOC entry 4871 (class 2606 OID 16626)
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- TOC entry 4873 (class 2606 OID 16635)
-- Name: leave_application leave_application_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.leave_application
    ADD CONSTRAINT leave_application_pkey PRIMARY KEY (id);


-- Completed on 2026-02-11 23:08:25

--
-- PostgreSQL database dump complete
--

\unrestrict NPAf9eP8ULVtHMkjEz7n1PtB7fB40sJyz27aD76mnHoFaKDzJbTzcSmoKaFpLFg

